spring:
  application:
    name: currency-conversion
  config:
    import:
      - optional:configserver:http://localhost:8888
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
server:
  port: 8100

resilience4j:
  circuitbreaker:
    instances:
      paymentsApi:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      paymentsApi:
        maxAttempts: 3
        waitDuration: 200ms
        retryExceptions:
          - java.net.SocketTimeoutException
          - org.springframework.web.client.ResourceAccessException

