spring:
  application:
    name: explore-tech-security

  config:
    import:
      - optional:configserver:http://localhost:8888

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cms
      username: root
      #password: lomatech
      password: mysqlpassword
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
      properties:
        max_allowed_packet: 2000

jwt:
  secretKey: jldafjlkjdlaksjldjfalskjldkfajsljdlka854646sdfadfasfdasdfasfj