spring:
  application:
    name: currency-exchange

  config:
    import:
      - optional:configserver:http://localhost:8888

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cms
      username: root
      password: mysqlpassword
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
      properties:
        max_allowed_packet: 2000

resilience4j:
  retry:
    instances:
      sample-api:
        maxAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
  circuitbreaker:
    instances:
      sample-api:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        #recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
  bulkhead:
    instances:
      sample-api:
        maxConcurrentCalls: 10
        maxWaitDuration: 0 # how long extra calls should wait for a slot
      sampleBulkheadDemo:
        maxConcurrentCalls: 2
        maxWaitDuration: 0
server:
  port: 8000