cloud:
  aws:
    region:
      static: ap-southeast-2
      auto: false
    credentials:
      access-key:
      secret-key:
    end-point:
      uri: arn:aws:sns:ap-southeast-2:796973505063:explorertech-topic